Feature/bypass capatcha
fjcaetano/ReCaptcha pull request #50
Opened 2018-09-10 10:47 UTC by Przemyslaw-Wosko

2018-09-10 18:19 UTC, fjcaetano requested changes
Awesome stuff, @Przemyslaw-Wosko, thanks for these changes.

- Please, squash these changes into one commit and give it a friendly message. Don't forget to add `fix #51` to close your related issue.
- Also, it'd be amazing if you could write a test case to ensure this is behaving as intended.
- Lastly, what do you think of editing README with a straightforward example of how to use this in a test?

2018-09-10 18:19 UTC, fjcaetano commented on ReCaptcha/Classes/ReCaptcha.swift
> +    public static var shouldSkipForUITests = false
I'd wrap this in `#if DEBUG`, since this is **not** something a developer wants enabled in production.

Take a look at `forceVisibleChallenge`, I'd go for a similar approach.

2018-09-10 18:19 UTC, fjcaetano commented on ReCaptcha/Classes/ReCaptcha.swift
> +        }
Similarly, this can be left as was and handle this from within `ReCaptchaWebViewManager.validate` with something like this:

``` swift
func validate (...) ->
  guard !shouldSkipForUITests else {
    completion(.token("")) // Maybe add a message here e.g. "fake validation test"
    return
  }
 ...
}
```

2018-09-10 18:19 UTC, fjcaetano commented on ReCaptcha/Classes/ReCaptchaWebViewManager.swift
> -
Please, revert this back.

2018-09-14 23:58 UTC, Przemyslaw-Wosko commented
@fjcaetano thank you for review!
Those changes are just beta-changes to get this workaround, i fully agree with your comments and i was aware that i should make them before PR, but i wanted to check out if you would merge feature like that ;) 

Anyway that was busy week and i'm trying to improve this code.

2018-09-15 00:04 UTC, Przemyslaw-Wosko commented on ReCaptcha/Classes/ReCaptcha.swift
> +    public static var shouldSkipForUITests = false
sure, aside from that, CI should also just build app for RELEASE configuration, just to make surea that code will compile.

2018-09-15 00:07 UTC, Przemyslaw-Wosko commented on ReCaptcha/Classes/ReCaptcha.swift
> +        }
Acually i think that this message should be configurable, but i won't do it in this PR, what do you think?

2018-09-15 00:08 UTC, Przemyslaw-Wosko commented on ReCaptcha/Classes/ReCaptchaWebViewManager.swift
> -
done

2018-09-27 18:22 UTC, fjcaetano commented
Merged.

2018-09-27 18:22 UTC, closed without merging